version: '3'

services:

  gogocarto:
    build: server
    container_name: gogocarto
    volumes:
      - ..:/var/www
      - /var/www/var/cache
      - /var/www/var/log
      - /var/www/var/sessions
      - /var/www/web/uploads
    ports:
      - "3008:80"
    links:
      - mongo:mongo
    tty: true

  mongo:
    image: shikhir/alpine-mongodb
    container_name: mongo
    volumes:
      - mongo:/data/mongodb
    ports:
      - "27017:27017"
    tty: true

volumes:
  mongo: {}
